# Question 1:

Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

#### HINT: 
Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.


In [1]:
import numpy as np

In [10]:
def result_matrix(input, col, increment=False):
    if not increment:
        output_matrix = np.array([j**(col-1-i) for j in input for i in range(col)]).reshape(input.size,col)
    elif increment:
        output_matrix = np.array([j**i for j in input for i in range(col)]).reshape(input.size,col)
    return output_matrix

In [15]:
result_matrix(np.array([2,3,4,5]), 3, False)

array([[ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [17]:
result_matrix(np.array([2,3,4,5]), 3, True)

array([[ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

In [18]:
result_matrix(np.array([1,2,3,4,5]), 5, True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [19]:
result_matrix(np.array([1,2,3,4,5]), 5, False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

# Question 2

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [117]:
def moving_avg(list, k):
    ac_sum = [0]
    m_avg = []
    for i, l in enumerate(list, 1):
        ac_sum.append(ac_sum[i-1] + l)
        if i>=k:
            m_avgs = round(((ac_sum[i] - ac_sum[i-k])/k),3)
            m_avg.append(m_avgs)
            
    print("Moving averages are with window size {} are:".format(k),m_avg)
    
        
        
    

In [118]:
moving_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

Moving averages are with window size 3 are: [5.0, 4.667, 5.667, 6.667, 9.667, 28.667, 49.333, 72.667, 84.0, 93.333, 116.333]
